
- name: Configure Nginx port
  hosts: all
  become: yes

  tasks:
    - name: Allow port in SELinux
      seport:
        ports: "{{ target_port }}"
        proto: tcp
        setype: http_port_t
        state: present

    - name: Update Nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/custom_port.conf
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
