- name: Nginx Custom Port
  hosts: all
  become: yes
  vars:
    target_port: 8085

  tasks:
    - name: Validate port
      chek:
        port: "{{ target_port }}"

    - name: SELinux allow port
      seport:
        ports: "{{ target_port }}"
        proto: tcp
        setype: http_port_t
        state: present

    - name: Config Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/custom_port.conf
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
